// <auto-generated />
using System;
using Hs.DatabaseAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hs.DatabaseAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231126111344_addImageUrlToProduct")]
    partial class addImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hs.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2023, 11, 26, 15, 13, 44, 83, DateTimeKind.Local).AddTicks(38),
                            DisplayOrder = 1,
                            Name = "Guitars"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2023, 11, 26, 15, 13, 44, 83, DateTimeKind.Local).AddTicks(49),
                            DisplayOrder = 2,
                            Name = "Drums"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2023, 11, 26, 15, 13, 44, 83, DateTimeKind.Local).AddTicks(51),
                            DisplayOrder = 3,
                            Name = "Piano"
                        });
                });

            modelBuilder.Entity("Hs.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brandname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prices")
                        .HasColumnType("float");

                    b.Property<string>("Productname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantities")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brandname = "Ibanez",
                            CategoryId = 1,
                            Description = "This Guiter is electric",
                            ImageUrl = "",
                            Prices = 1250.0,
                            Productname = "Guitar",
                            Quantities = 20.0
                        },
                        new
                        {
                            Id = 2,
                            Brandname = "Fender",
                            CategoryId = 3,
                            Description = "This piano is from Fender",
                            ImageUrl = "",
                            Prices = 2550.0,
                            Productname = "Piano",
                            Quantities = 13.0
                        },
                        new
                        {
                            Id = 3,
                            Brandname = "Gibson Brand, Inc",
                            CategoryId = 2,
                            Description = "This Guiter is from Gibson Brand, Inc",
                            ImageUrl = "",
                            Prices = 3450.0,
                            Productname = "Drum",
                            Quantities = 4.0
                        });
                });

            modelBuilder.Entity("Hs.Models.Product", b =>
                {
                    b.HasOne("Hs.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
