// <auto-generated />
using System;
using Hs.DatabaseAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hs.DatabaseAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231119150647_addproductToDb")]
    partial class addproductToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hs.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2023, 11, 19, 19, 6, 47, 16, DateTimeKind.Local).AddTicks(3778),
                            DisplayOrder = 1,
                            Name = "Home Interiors"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2023, 11, 19, 19, 6, 47, 16, DateTimeKind.Local).AddTicks(3798),
                            DisplayOrder = 2,
                            Name = "Clothes & wears"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2023, 11, 19, 19, 6, 47, 16, DateTimeKind.Local).AddTicks(3800),
                            DisplayOrder = 3,
                            Name = "Computer & tech"
                        });
                });

            modelBuilder.Entity("Hs.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("brandname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 20,
                            brandname = "Ibanez",
                            pdesc = "This Guiter is electric",
                            pname = "Guitar",
                            price = 1250
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 13,
                            brandname = "Fender",
                            pdesc = "This Guiter is from Fender",
                            pname = "Piano",
                            price = 2550
                        },
                        new
                        {
                            Id = 3,
                            Quantity = 4,
                            brandname = "Gibson Brand, Inc",
                            pdesc = "This Guiter is from Gibson Brand, Inc",
                            pname = "Drum",
                            price = 3450
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
